try tagging, only deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,101 +90,101 @@ commands:
 
 
 jobs:
-  go_lint_and_analyze:
-    executor: go_docker
-    steps:
-      - checkout
-      - run:
-          name: Lint the Go cmd/web
-          command: gofmt -d ./cmd/web
-      - run:
-          name: Lint the Go pkg/
-          command: gofmt -d ./pkg
-      - run:
-          name: Run static analyzer on cmd/web
-          command: go vet ./cmd/web
-      - run:
-          name: Run static analyzer on pgk
-          command: |
-            go vet ./pkg/forms
-            go vet ./pkg/models
-            go vet ./pkg/models/mock
-            go vet ./pkg/models/mysql
+  # go_lint_and_analyze:
+  #   executor: go_docker
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Lint the Go cmd/web
+  #         command: gofmt -d ./cmd/web
+  #     - run:
+  #         name: Lint the Go pkg/
+  #         command: gofmt -d ./pkg
+  #     - run:
+  #         name: Run static analyzer on cmd/web
+  #         command: go vet ./cmd/web
+  #     - run:
+  #         name: Run static analyzer on pgk
+  #         command: |
+  #           go vet ./pkg/forms
+  #           go vet ./pkg/models
+  #           go vet ./pkg/models/mock
+  #           go vet ./pkg/models/mysql
 
-  lint_docker_compose:
-    executor: go_docker
-    steps:
-      - checkout
-      - run:
-          name: Install Docker compose
-          command: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-      - run:
-          name: Lint Docker-Compose config
-          command: docker-compose config -q
+  # lint_docker_compose:
+  #   executor: go_docker
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install Docker compose
+  #         command: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+  #     - run:
+  #         name: Lint Docker-Compose config
+  #         command: docker-compose config -q
 
-  lint_dockerfiles:
-    executor: hadolint
-    steps:
-      - checkout
-      - run:
-          name: Lint Dockerfiles
-          command: |
-            hadolint ./docker/app/Dockerfile --ignore DL3003 --ignore DL3059
-            hadolint ./docker/db/Dockerfile --ignore DL3003 --ignore DL3059
+  # lint_dockerfiles:
+  #   executor: hadolint
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Lint Dockerfiles
+  #         command: |
+  #           hadolint ./docker/app/Dockerfile --ignore DL3003 --ignore DL3059
+  #           hadolint ./docker/db/Dockerfile --ignore DL3003 --ignore DL3059
 
 
-  unit-tests:
-    executor: go_docker_and_mysql
-    parallelism: 2
-    working_directory: ~/project
-    environment:
-      TEST_RESULTS: /tmp/test-results
-      CODE_COVERAGE: /tmp/code_coverage
-    steps:
-      - checkout
-      - restore_go_cache
-      - run: mkdir -p /tmp/code_coverage/
-      - run: mkdir -p $TEST_RESULTS
-      - run: |
-          sudo apt-get update
-          sudo apt-get install default-mysql-client
-      - run:
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
-      - run:
-          name: Create test mysql table and user
-          command: |
-            mysql -h 127.0.0.1 --ssl-mode=DISABLED --user=root --password=snippet_root_pass --execute="CREATE DATABASE test_snippetbox CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
-            mysql -h 127.0.0.1 --ssl-mode=DISABLED --user=root --password=snippet_root_pass --execute="CREATE USER 'test_web'@'localhost'; \
-            GRANT CREATE, DROP, ALTER, INDEX, SELECT, INSERT, UPDATE, DELETE ON test_snippetbox.* TO 'test_web'@'localhost'; \
-            ALTER USER 'test_web'@'localhost' IDENTIFIED BY 'testing123';"
-      - run:
-          name: Run Go unit tests with coverage
-          command: |
-            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
-            gotestsum --junitfile ${TEST_RESULTS}/unit-tests-report.xml -- -coverprofile=${CODE_COVERAGE}/profile.out ./... $PACKAGE_NAMES
-      - store_test_results:
-          path: /tmp/test-results
-      - store_artifacts:
-          path: /tmp/code_coverage/profile.out
-      - save_cache:
-          key: go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
-          paths:
-            - "./"
+  # unit-tests:
+  #   executor: go_docker_and_mysql
+  #   parallelism: 2
+  #   working_directory: ~/project
+  #   environment:
+  #     TEST_RESULTS: /tmp/test-results
+  #     CODE_COVERAGE: /tmp/code_coverage
+  #   steps:
+  #     - checkout
+  #     - restore_go_cache
+  #     - run: mkdir -p /tmp/code_coverage/
+  #     - run: mkdir -p $TEST_RESULTS
+  #     - run: |
+  #         sudo apt-get update
+  #         sudo apt-get install default-mysql-client
+  #     - run:
+  #         name: Waiting for MySQL to be ready
+  #         command: |
+  #           for i in `seq 1 10`;
+  #           do
+  #             nc -z 127.0.0.1 3306 && echo Success && exit 0
+  #             echo -n .
+  #             sleep 1
+  #           done
+  #           echo Failed waiting for MySQL && exit 1
+  #     - run:
+  #         name: Create test mysql table and user
+  #         command: |
+  #           mysql -h 127.0.0.1 --ssl-mode=DISABLED --user=root --password=snippet_root_pass --execute="CREATE DATABASE test_snippetbox CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
+  #           mysql -h 127.0.0.1 --ssl-mode=DISABLED --user=root --password=snippet_root_pass --execute="CREATE USER 'test_web'@'localhost'; \
+  #           GRANT CREATE, DROP, ALTER, INDEX, SELECT, INSERT, UPDATE, DELETE ON test_snippetbox.* TO 'test_web'@'localhost'; \
+  #           ALTER USER 'test_web'@'localhost' IDENTIFIED BY 'testing123';"
+  #     - run:
+  #         name: Run Go unit tests with coverage
+  #         command: |
+  #           PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
+  #           gotestsum --junitfile ${TEST_RESULTS}/unit-tests-report.xml -- -coverprofile=${CODE_COVERAGE}/profile.out ./... $PACKAGE_NAMES
+  #     - store_test_results:
+  #         path: /tmp/test-results
+  #     - store_artifacts:
+  #         path: /tmp/code_coverage/profile.out
+  #     - save_cache:
+  #         key: go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
+  #         paths:
+  #           - "./"
 
-  build:
-    executor: machine_with_dlc
-    steps:
-      - checkout
-      - restore_go_cache
-      - build_container
+  # build:
+  #   executor: machine_with_dlc
+  #   steps:
+  #     - checkout
+  #     - restore_go_cache
+  #     - build_container
 
   deploy:
     executor: machine_with_dlc
@@ -197,7 +197,7 @@ jobs:
           name: Build app and db
           command: |
             echo $DOCKER_PASS | docker login -u $DOCKER_USERNAME --password-stdin
-            docker-compose build -t nicks-testing
+            docker-compose build -t 660990364978.dkr.ecr.us-east-2.amazonaws.com/nicks-testing:latest
       - run:
           name: Push images to dockerhub
           command: docker-compose push 660990364978.dkr.ecr.us-east-2.amazonaws.com/nicks-testing:latest
@@ -205,56 +205,56 @@ jobs:
 workflows:
   build-test-and-deploy:
     jobs:
-      - go_lint_and_analyze
-      - lint_docker_compose
-      - lint_dockerfiles
-      - build:
-          requires:
-              - go_lint_and_analyze
-              - lint_docker_compose
-              - lint_dockerfiles
-      - unit-tests:
-          requires:
-            - go_lint_and_analyze
-            - lint_docker_compose
-            - lint_dockerfiles
-      - cypress/install
-      - cypress/run:
-          name: cypress-tests
-          executor: machine_with_dlc
-          parallel: true
-          parallelism: 2
-          requires:
-            - build
-            - unit-tests
-            - cypress/install
-          pre-steps:
-            - checkout
-            - run:
-                'circleci tests glob "**/**/*.spec.js" | circleci tests split >
-                /tmp/tests.txt'
-            - run: |
-                    sudo apt-get update
-                    sudo apt-get install -y libgbm-dev
-            - start_app_and_verify
-            - restore_cache:
-                keys:
-                  - cypress-v2{{ .Branch }}-{{ checksum "package.json" }}
-                  - cypress-v2{{ .Branch }}
-                  - cypress-v2
-            - save_cache:
-                key: cypress-v2{{ .Branch }}-{{ checksum "package.json" }}
-                paths:
-                  - ~/.npm
-                  - ~/.cache
-          post-steps:
-            - store_test_results:
-                path: test-results
-          record: true
-          command: npx cypress run --spec $(cat /tmp/tests.txt)
+  #     - go_lint_and_analyze
+  #     - lint_docker_compose
+  #     - lint_dockerfiles
+  #     - build:
+  #         requires:
+  #             - go_lint_and_analyze
+  #             - lint_docker_compose
+  #             - lint_dockerfiles
+  #     - unit-tests:
+  #         requires:
+  #           - go_lint_and_analyze
+  #           - lint_docker_compose
+  #           - lint_dockerfiles
+  #     - cypress/install
+  #     - cypress/run:
+  #         name: cypress-tests
+  #         executor: machine_with_dlc
+  #         parallel: true
+  #         parallelism: 2
+  #         requires:
+  #           - build
+  #           - unit-tests
+  #           - cypress/install
+  #         pre-steps:
+  #           - checkout
+  #           - run:
+  #               'circleci tests glob "**/**/*.spec.js" | circleci tests split >
+  #               /tmp/tests.txt'
+  #           - run: |
+  #                   sudo apt-get update
+  #                   sudo apt-get install -y libgbm-dev
+  #           - start_app_and_verify
+  #           - restore_cache:
+  #               keys:
+  #                 - cypress-v2{{ .Branch }}-{{ checksum "package.json" }}
+  #                 - cypress-v2{{ .Branch }}
+  #                 - cypress-v2
+  #           - save_cache:
+  #               key: cypress-v2{{ .Branch }}-{{ checksum "package.json" }}
+  #               paths:
+  #                 - ~/.npm
+  #                 - ~/.cache
+  #         post-steps:
+  #           - store_test_results:
+  #               path: test-results
+  #         record: true
+  #         command: npx cypress run --spec $(cat /tmp/tests.txt)
       - deploy:
-          requires:
-            - cypress-tests
+          # requires:
+          #   - cypress-tests
           context:
             - hello-context
           # filters:
